MTES-MCT/Dossier-Facile-Frontend

tenant/src/components/GuarantorDocuments.vue, tenant/src/components/documents/GuarantorIdentification.vue, tenant/src/components/documents/Identification.vue, tenant/src/store/index.ts
fix missing translation on required fields
=> feat(guarantor): fix code when adding guarantor on unfilled guarantor

tenant/src/components/documents/DocumentTypeConstants.ts, tenant/src/components/documents/Financial.vue, tenant/src/components/documents/GuarantorFinancial.vue, tenant/src/components/documents/GuarantorTax.vue, tenant/src/components/documents/Tax.vue
specify noDocument for backend
=> feat(documents): replace wrong trading translation by scholarship

df-shared/src/Button/BigRadio.vue, tenant/src/components/CoupleInformation.vue, tenant/src/components/RoommatesInformation.vue, tenant/src/components/TenantInformationForm.vue, tenant/src/components/documents/Tax.vue, tenant/src/store/index.ts, tenant/src/views/Account.vue, tenant/src/views/Profile.vue
and lot of style improvements thanks to michael
=> chore: remember cotenant and spouse check

df-shared/src/GouvFr/v-gouv-fr-modal/VGouvFrModal.vue
fix the menu opener but disallow to close modal by clicking outside the modal
=> feat(modal): use Vue code to open and close modal

tenant/src/components/uploads/ListItem.vue
Avoid text overflow on documents
=> feat(documents): improve style on mobile

tenant/src/main.ts, tenant/src/store/index.ts
check if the user is logged in when initializing keycloak
=> fix: 🐛 check login on init

tenant/src/views/Account.vue
Add warning message when a guarantor document is declined
=> fix(account): 🐛 Fix warning message

tenant/src/components/documents/Financial.vue, tenant/src/components/documents/GuarantorFinancial.vue, tenant/src/components/footer/BackNext.vue, tenant/src/components/footer/FinancialFooter.vue, tenant/src/components/footer/GuarantorFooter.vue
Add the potential third button to the same line on desktop
=> style: 💄 Improve footer style

tenant/src/views/Account.vue, tenant/src/views/ChangePasswordPage.vue
This will redirect to the right page if the account is incomplete
=> feat: 🎸 Redirect to /account on password-change

tenant/src/components/GuarantorChoice.vue
Use email as key for local storage to avoid same option on multiple
accounts
=> chore(guarantor): 🤖 Save guarantorChoice by email

tenant/src/components/DeleteAccount.vue
We don't want to ask for password anymore
=> feat(profile): 🎸 Remove password confirmation from delete

df-shared/src/GouvFr/v-gouv-fr-modal/VGouvFrModal.vue
=> fix: 🐛 Set button type to close modal button

tenant/src/components/documents/GuarantorFinancialDocumentForm.vue, tenant/src/store/index.ts
Fix save, use Vue.set to update store
=> fix(guarantor): 🐛 Fix guarantor financial files save

main/src/views/LandingPage.vue
ajout d’un intitulé pertinent sur une série d’images-liens de sites partenaires et ajout de l’indication correspondant de navigation « nouvelle fenêtre », en application du principe de moindre surprise pour l’usager
=> améliorations d’accessibilité

tenant/src/components/documents/legalPersonGuarantor/CorporationIdentification.vue, tenant/src/components/documents/legalPersonGuarantor/RepresentativeIdentification.vue, tenant/src/components/documents/organismGuarantor/OrganismCert.vue
when documentDeniedReasons is missing
=> fix(guarantor): 🐛 Avoid npe for some pages

tenant/src/services/ProfileService.ts, tenant/src/store/index.ts
Redirect franceConnect to firstpage to update zipcode if empty and
modify the way we save for franceConnect
=> feat: 🎸 Improve franceConnect redirect and save

tenant/src/components/GuarantorChoice.vue
This reverts commit 44453308f40b350d8c8167ff4dfe8befac048463.
=> Revert "feat(guarantor): 🎸 set no_guarantor as default value"

tenant/src/components/documents/tenant/Tax.vue
And thus when a change is made
=> fix(profile): 🐛 Fix save when a file is added

main/src/views/MentionsLegales.vue
Ajout d'une couleur de fond dans la partie .imagebg (pour une bonne lisibilité si absence d'image de fond)
=> Ajout background-color

main/src/views/404.vue, main/src/views/Information.vue
Ajout d'une couleur d'arrière plan pour permettre la lecture du titre de la page s'il manquait le visuel.
=> Add background-color

main/public/index.html, main/server.js, main/src/router/index.ts, yarn.lock
Remove history on main to have ssr only
=> feat: 🎸 Add image as open graph meta

main/.slugignore, tenant/.slugignore
We need some node_modules for node server but it's available with
nohoist
=> chore: 🤖 Remove all upstream node_modules

main/.env, tenant/.env, tenant/src/store/index.ts
if there is no zipcode but there are documents we redirect right
=> feat(tenant): redirect to right page

df-shared/src/models/FileUser.ts, tenant/src/views/File.vue
Wait Back decision before merging
=> feat(file): use pdf status instead link

.gitignore, owner/cypress.config.ts, owner/cypress/e2e/login.cy.ts, owner/cypress/fixtures/example.json, owner/cypress/fixtures/profile.json, owner/cypress/fixtures/users.json, owner/cypress/support/commands.ts, owner/cypress/support/e2e.ts, owner/package.json, yarn.lock
=> feat(owner): 🎸 Add cypress

tenant/src/views/Account.vue
TODO : see to extract code to main.scss
=> style(tenant): 💄 Fix icon css

tenant/src/router/index.ts
and reduce updateMessages call
=> feat(tenant): Avoid multiple updateToken workers

tenant/src/components/documents/naturalGuarantor/GuarantorProfessional.vue, tenant/src/locales/en.json, tenant/src/locales/fr.json
=> feat(tenant): 🎸 Add translation for cotenant guarantor

tenantv3/src/components/TenantMenu.vue
Also use router-link, <a> was an old hack for DSFR
=> fix(menu): 🐛 Fix selected item on menu

owner/src/components/LandingPage.vue, owner/src/locales/en.json, owner/src/locales/fr.json
J'ai pris en compte vos remarques
J'ai MAJ les textes de la home owner uniquement pour l'instant.
Je verrais plus tard pour la partie CSS/HTML
Au vu du faible trafic anglophone, je n'ai pas traduit en anglais. Mais je peux le faire.
=> Landing owner2

tenantv3/src/components/documents/cotenant/CoTenantFinancialForm.vue, tenantv3/src/components/documents/naturalGuarantor/GuarantorFinancialDocumentForm.vue, tenantv3/src/components/documents/tenant/FinancialDocumentForm.vue, tenantv3/src/locales/en.json, tenantv3/src/locales/fr.json
=> ✨ Feat(financial): trunk monthly sum to avoid error

tenantv3/package.json, tenantv3/vite.config.ts, yarn.lock
This reverts commit 3798daa78ffb2cb369cc2e4395893ffd767c5076.
Messages from locales are not properly translated with the new plugin
=> Revert "⬆️  build: Replace deprecated vue-plugin-i18n"

tenantv3/src/components/documents/naturalGuarantor/GuarantorFinancialDocumentForm.vue, tenantv3/src/components/documents/tenant/FinancialDocumentForm.vue
structuredClone does not work on proxy object, need to use toRaw
=> 🐛 Fix(tenant): DataCloneError in FinancialDocument

df-shared-next/src/components/ToggleComponent.vue, tenantv3/src/components/SharedLinks.vue
=> 🐛 Fix: error in console - this.input is undefined

df-shared-next/src/models/User.ts, tenantv3/src/components/NameInformationForm.vue, tenantv3/src/locales/en.json, tenantv3/src/locales/fr.json
Password enabled was always false since password is on keycloak
=> refactor(tenant): 💡 Remove old unused feature with password

tenantv3/src/components/messaging/MessagesPanel.vue
Don't hide old messages when sending a new message Scroll user to the message he just sent
=> ✨ Feat(tenant): Messaging - keep old messages

www/src/router/index.ts, www/src/views/blog/ArticlePage26.vue, www/src/views/blog/BlogView.vue
=> ✨ Feat: www - add new blog article

tenantv3/src/stores/tenant-store.ts
Workaround for bad transaction handling on backend: if no document data is present in the response, refetch data
=> 🚑️ Hotfix: refetch data on upload

tenantv3/src/components/documents/share/PreValidationMessages.vue, tenantv3/src/components/documents/tenant/TenantTax.vue, tenantv3/src/components/financial/lib/UploadFilesFinancial.vue
=> Feat(tenant): Add blurry validation warning

owner/src/components/account/NameInformationForm.vue, tenantv3/src/components/TenantInformationForm.vue, tenantv3/src/services/UtilsService.ts
When the data from backend does not have a message field, don't crash
=> 🥅 Fix: crash in error handling

www/src/router/index.ts, www/src/views/blog/ArticlePage28.vue, www/src/views/blog/BlogView.vue
- Introduced a new route for the article "Étudiant étranger et recherche de logement : guide pratique".
- Created the ArticlePage28.vue component with comprehensive guidance for international students seeking housing in France.
- Updated BlogView.vue to include a preview tile for the new article.
=> ✨ Feat(blog): Add new article on housing for international students

tenantv3/src/components/account/ShareFile.vue
=> fix(tenant): add validation for email on application form

pnpm-lock.yaml, tenantv3/package.json, tenantv3/src/components/CoupleInformation.vue, tenantv3/src/components/common/GuarantorBadge.vue, tenantv3/src/components/common/TenantBadge.vue, tenantv3/src/components/documents/cotenant/CoTenantName.vue, tenantv3/src/components/documents/cotenant/CoupleFinancial.vue, tenantv3/src/components/documents/cotenant/CoupleProfessional.vue, tenantv3/src/components/documents/cotenant/CoupleResidency.vue, tenantv3/src/components/documents/cotenant/DocumentDownloader.vue, tenantv3/src/components/documents/legalPersonGuarantor/CorporationIdentification.vue, tenantv3/src/components/documents/legalPersonGuarantor/RepresentativeIdentification.vue, tenantv3/src/components/documents/naturalGuarantor/CoupleGuarantorResidency.vue, tenantv3/src/components/documents/naturalGuarantor/GuarantorFinancial.vue, tenantv3/src/components/documents/naturalGuarantor/GuarantorIdentification.vue, tenantv3/src/components/documents/naturalGuarantor/GuarantorName.vue, tenantv3/src/components/documents/naturalGuarantor/GuarantorProfessional.vue, tenantv3/src/components/documents/naturalGuarantor/GuarantorTax.vue, tenantv3/src/components/documents/naturalGuarantor/TenantGuarantorProfessional.vue, tenantv3/src/components/documents/organismGuarantor/OrganismCert.vue, tenantv3/src/components/documents/tenant/TenantFinancial.vue, tenantv3/src/components/documents/tenant/TenantIdentification.vue, tenantv3/src/components/documents/tenant/TenantMainActivity.vue, tenantv3/src/components/documents/tenant/TenantResidency.vue, tenantv3/src/components/documents/tenant/TenantTax.vue, tenantv3/src/components/financial/FinancialRecap.vue, tenantv3/src/components/guarantorResidency/GuarantorResidency.vue
=> ✨ Feat(tenant): Add Tenant/Guarantor badges

df-shared-next/src/Header/HeaderComponent.vue
=> ✨ Feat: change signup label in header

tenantv3/src/services/PdfAnalysisService.ts
This will improve performance on load, and fix Safari error on tax page
=> 🐛 Fix: load pdfjs asynchronously

df-shared-next/src/scss/_main.scss, owner/index.html, owner/src/App.vue, tenantv3/index.html, tenantv3/src/App.vue, watermark/index.html, watermark/src/App.vue, www/index.html, www/src/App.vue
Need to modify the MAIN_CSP env variable to all front containers in scalingo to allow img-src from the cdn
=> chore: add dossier-facile-cdn for better performances
